// <auto-generated />
namespace Mvc5Project.Migrations.FormExampleDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Form1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Form1));
        
        string IMigrationMetadata.Id
        {
            get { return "201811041446143_Form1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
